name: Convert Markdown to PDF

on:
  pull_request:
    paths:
      - 'Current_Constitution.md'
      - 'Current_Bylaws.md'
    branches: [ master ]

jobs:
  convert:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.ref }}
      - name: Prepare to Convert
        run: |
          sed "1s/#/%/; 2d; 3s/^/% /" Current_Constitution.md > convert_constitution.md
          sed "1s/#/%/; 2d; 3s/^/% /" Current_Bylaws.md > convert_bylaws.md
      - name: Convert Constitution
        uses: docker://pandoc/latex:2.9
        with:
          args: "--standalone --output=Current_Constitution.pdf convert_constitution.md"
      - name: Convert Bylaws
        uses: docker://pandoc/latex:2.9
        with:
          args: "--standalone --output=Current_Bylaws.pdf convert_bylaws.md"
      - name: Remove temp file
        run: rm -f convert_constitution.md convert_bylaws.md
      - name: Commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git commit -m "Update PDFs" -a
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.head_ref }}
  # convert_bylaws:
  #   needs: check_change
  #   runs-on: ubuntu-18.04
  #   steps:
  #     - uses: actions/checkout@v2
  #       with:
  #         ref: ${{ github.event.pull_request.head.ref }}
  #     - name: Prepare to Convert
  #       run: sed "1s/#/%/; 2d; 3s/^/% /" Current_Bylaws.md > convert_bylaws.md
  #     - name: Convert file
  #       uses: docker://pandoc/latex:2.9
  #       with:
  #         args: "--standalone --output=Current_Bylaws.pdf convert_bylaws.md"
  #     - name: Remove temp file
  #       run: rm -f convert_bylaws.md
  #     - name: Commit files
  #       run: |
  #         git config --local user.email "action@github.com"
  #         git config --local user.name "GitHub Action"
  #         git commit -m "Update Bylaws PDF" -a
  #     - name: Push changes
  #       uses: ad-m/github-push-action@master
  #       with:
  #         github_token: ${{ secrets.GITHUB_TOKEN }}
  #         branch: ${{ github.head_ref }}
